## Assignment #2 NLP
- reference for this part of the assignment from Advanced Natural Language Processing [CS 685, Spring 2022, UMass Amherst](https://people.cs.umass.edu/~miyyer/cs685/schedule.html)


#### IMPORTANT: After copying this notebook to your Google Drive, please paste a link to it below. To get a publicly-accessible link, hit the *Share* button at the top right, then click "Get shareable link" and copy over the result. If you fail to do this, you will receive no credit for this homework!
***LINK:***

---


##### *How to submit this problem set:*
- Write all the answers in this Colab notebook. Once you are finished, generate a PDF via (File -> Print -> Save as PDF) and upload it to Gradescope.
  
- **Important:** check your PDF before you submit to Gradescope to make sure it exported correctly. If Colab gets confused about your syntax, it will sometimes terminate the PDF creation routine early.

- When creating your final version of the PDF to hand in, please do a fresh restart and execute every cell in order. One handy way to do this is by clicking `Runtime -> Run All` in the notebook menu.

---

##### *Academic honesty*

- We will audit the Colab notebooks from a set number of students, chosen at random. The audits will check that the code you wrote actually generates the answers in your PDF. If you turn in correct answers on your PDF without code that actually generates those answers, we will consider this a serious case of cheating. See the course page for honesty policies.

- We will also run automatic checks of Colab notebooks for plagiarism. Copying code from others is also considered a serious case of cheating.

---

# Part 1: Annotation

In this homework, you will first collect a labeled dataset of **120** sentences for a text classification task of your choice. This process will include:

1. *Data collection*: Collect 120 sentences from any source you find interesting (e.g., literature, Tweets, news articles, reviews, etc.)

2. *Task design*: Come up with a binary (i.e., only two labels) sentence-level classification task that you would like to perform on your sentences. Be creative, and make sure your task isn't too easy (e.g., perhaps the labels have some degree of subjectivity to them, or the task is otherwise complex for humans). Write up annotator guidelines/instructions on how you would like people to label your data.

3. Everyone in this class will need to both create their own dataset and also serve as an annotator for another group. In order to get everything done on time, you need to complete the following steps:

> *   Find a group where each member is willing to label 120 sentences
*   Send them your annotation guidelines and a way that they can easily annotate the data (e.g., a spreadsheet or Google form)
*   Collect the labeled data from each of the annotators.
*   Sanity check the data for basic cleanliness (are all examples annotated? are all labels allowable ones?)

4. Collect feedback from annotators about the task including annotation time and obstacles encountered (e.g., maybe your guidelines were confusing! or maybe some sentences were particularly hard to annotate!)

5. Aggregate output from both annotators to create final dataset.

6. Perform NLP experiments on your new dataset!

## Question 1.1 (10 points):
Describe the source of your unlabeled data, why you chose it, and what kind of sentence selection process you used (if any) to choose 120 sentences for annotation. Also briefly describe the text classification task that you will be collecting labels for in the next section.

### *WRITE YOUR ANSWER HERE* ###
__Abstract:
We have scraped data from twitter based on the keyword “elections”, since we are only interested in 120 sentences, so we decided to limit our tweet scope to Atlanta. We have scraped more than 10000 tweets and filtered them based on word count of tweets, we have chosen only tweet lengths greater than 53 and then scanned every tweet and filtered them further to come with 120 tweets.__<br>

## Question 1.2 (25 points):
Copy the annotation guidelines that you provided to your classmates below. You must include:

> *   The two categories for your binary classification problem, including the exact strings you want annotators to use while labeling. 
*   Descriptions of the categories and what they mean.
*   Representative examples of each category (i.e., sentences from outside your dataset that you have manually labeled to give annotators an idea of how to perform the task)
*   A discussion of of tricky corner cases, and criteria to help the annotator decide them. If you look at the data and think about how an annotator could do the task, you will likely find a bunch of these!


---


### *COPY YOUR ANNOTATION GUIDELINES HERE.* Please format them nicely so it's easy to read / grade :)### 
__Instructions for Labeling:
We have a text column; we want you to label the text column based on whether the tweet is negative or not negative based on your understanding of the tweet. For e.g.,<br>
_@Truth_Tornado @CNN @jaketapper Again...you are believing a lie because it f its a narrative which you already accept. There were no lines anywhere in GA on Election Day in 2020. The law on water is no 3rd party can enter the 150 ft area near polling to do it. You are being lied to for political rea sons._<br>
In the above tweet, we can clearly identify that the tweet is negative. Similarly, we want you to label the data.
Some approach to make the task easier,<br>
Steps:
Read the file in python using df = pandas.read.csv(filename) Then pass a for loop<br>
for i in range(len(df)):<br>
print("\n") <br>
print(i) <br>
print(df.iloc[i])<br>
This code will give you all the tweets in a much readable format.<br>
Once you have all the sentences, analyze them, and create two lists to store index numbers of negative and not negative tweets. And once the list is finalized create two labels “negative” and “not negative” and update them in the label column.<br>
You can use any other approaches that are convenient to you as well. Thank you.__

## Question 1.3 (5 points):
Once they are finished annotating, create two .csv files (annotator1.csv, annotator2.csv etc) that contains each annotator's labels. The file should have two columns with headers **text** and **label**, respectively. 


## Question 1.4 (10 points):
After both annotators have finished labeling the 120 sentences you gave them, ask them for feedback about your task and the provided annotation guidelines. If you were to collect more labeled data for this task in the future, what would you change from your current setup? Why? Please include a summary of annotator feedback (with specific examples that they found challenging to label) in your answer.

### *WRITE ANSWER HERE* ###
__They found it difficult to label it into two classes since there were multiclass problems, in our case it was positive,negative and neutral, but we only had the option to do 2 classes so we went with negative and non negative,which can be challenging sometimes.__

## Question 1.5 (10 points):
To form your final dataset, you need to *aggregate* the annotations from both annotators (i.e., for cases where they disagree, you need to choose a single label). Use any method you like other than random label selection to perform this aggregation (e.g., have the annotators discuss each disagreement and come to consensus, or choose the label you agree with the most). Upload your final dataset to the Colab session (in the same format as the other two files) as final_dataset.csv. Remember to include this file in your final submission!

### *DESCRIBE YOUR AGGREGATION STRATEGY HERE* ###
__We went through each tweet that were differently labeled and labeled what we felt according to our instinct__

# Part 2: Text classification

Now we'll move onto fine-tuning  pretrained language models specifically on your dataset. This part of the homework is meant to be an introduction to the HuggingFace library, and it contains code that will potentially be useful for your final projects. Since we're dealing with large models, the first step is to change to a GPU runtime.

## Adding a hardware accelerator

Please go to the menu and add a GPU as follows:

`Edit > Notebook Settings > Hardware accelerator > (GPU)`

Run the following cell to confirm that the GPU is detected.

In [2]:
import torch

# Confirm that the GPU is detected

assert torch.cuda.is_available()

# Get the GPU device name.
device_name = torch.cuda.get_device_name()
n_gpu = torch.cuda.device_count()
print(f"Found device: {device_name}, n_gpu: {n_gpu}")
device = torch.device("cuda")

Found device: Tesla T4, n_gpu: 1


## Installing Hugging Face's Transformers library
We will use Hugging Face's Transformers (https://github.com/huggingface/transformers), an open-source library that provides general-purpose architectures for natural language understanding and generation with a collection of various pretrained models made by the NLP community. This library will allow us to easily use pretrained models like `BERT` and perform experiments on top of them. We can use these models to solve downstream target tasks, such as text classification, question answering, and sequence labeling.

Run the following cell to install Hugging Face's Transformers library and download a sample data file called tweets.csv that contains tweets about airlines along with a negative, neutral, or positive sentiment rating. Note that you will be asked to link with your Google Drive account to download some of these files. If you're concerned about security risks (there have not been any issues in previous semesters), feel free to make a new Google account and use it for this homework!

In [3]:
!pip install transformers
!pip install -U -q PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
print('success!')

import os
import zipfile

# Download helper functions file
helper_file = drive.CreateFile({'id': '16HW-z9Y1tM3gZ_vFpJAuwUDohz91Aac-'})
helper_file.GetContentFile('helpers.py')
print('helper file downloaded! (helpers.py)')

# Download sample file of tweets
data_file = drive.CreateFile({'id': '1QcoAmjOYRtsMX7njjQTYooIbJHPc6Ese'})
data_file.GetContentFile('tweets.csv')
print('sample tweets downloaded! (tweets.csv)')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.5 MB 14.9 MB/s 
     |████████████████████████████████| 163 kB 65.9 MB/s 
     |████████████████████████████████| 7.6 MB 32.6 MB/s 
success!
helper file downloaded! (helpers.py)
sample tweets downloaded! (tweets.csv)


The cell below imports some helper functions we wrote to demonstrate the task on the sample tweet dataset.

In [4]:
from helpers import tokenize_and_format, flat_accuracy

# Part 1: Data Prep and Model Specifications

Upload your data using the file explorer to the left. We have provided a function below to tokenize and format your data as BERT requires. Make sure that your csv file, titled final_data.csv, has one column "text" and another column "labels" containing integers.

If you run the cell below without modifications, it will run on the tweets.csv example data we have provided. It imports some helper functions we wrote to demonstrate the task on the sample tweet dataset. You should first run all of the following cells with tweets.csv just to see how everything works. Then, once you understand the whole preprocessing / fine-tuning process, change the csv in the below cell to your final_data.csv file, add any extra preprocessing code you wish, and then run the cells again on your own data.

In [6]:
import pandas as pd
final_data = pd.read_csv('/content/final_data.csv')
final_data.head()

Unnamed: 0                                             Text_x  label
0           0  @FordThunderman @slayadidanca @CapiLady @nypos...      0
1           1  @michael_rich29 @GbengaGOLD @PeterObi Are u ev...      1
2           2  @CharmedbyKaren @GabrielSterling I believe any...      1
3           3  @Truth_Tornado @CNN @jaketapper Again…you are ...      1
4           4  @Mary1Kathy @lyndah612 @lisasmith1150 @GulliAz...      0

In [7]:
final_data = final_data.iloc[:,1:]
final_data.head()

Text_x  label
0  @FordThunderman @slayadidanca @CapiLady @nypos...      0
1  @michael_rich29 @GbengaGOLD @PeterObi Are u ev...      1
2  @CharmedbyKaren @GabrielSterling I believe any...      1
3  @Truth_Tornado @CNN @jaketapper Again…you are ...      1
4  @Mary1Kathy @lyndah612 @lisasmith1150 @GulliAz...      0

In [8]:
final_data.isna().sum()

Text_x    0
label     0
dtype: int64

In [9]:
final_data.rename(columns={'Text_x':'text'},inplace=True)

In [10]:
df = final_data.copy()

In [11]:
df.head()

text  label
0  @FordThunderman @slayadidanca @CapiLady @nypos...      0
1  @michael_rich29 @GbengaGOLD @PeterObi Are u ev...      1
2  @CharmedbyKaren @GabrielSterling I believe any...      1
3  @Truth_Tornado @CNN @jaketapper Again…you are ...      1
4  @Mary1Kathy @lyndah612 @lisasmith1150 @GulliAz...      0

In [12]:
from helpers import tokenize_and_format, flat_accuracy
import pandas as pd

#df = pd.read_csv('final_data.csv')
#df = pd.read_csv('tweets.csv')

df = df.sample(frac=1).reset_index(drop=True)

texts = df.text.values
labels = df.label.values

### tokenize_and_format() is a helper function provided in helpers.py ###
input_ids, attention_masks = tokenize_and_format(texts)

# Convert the lists into tensors.
input_ids = torch.cat(input_ids, dim=0)
attention_masks = torch.cat(attention_masks, dim=0)
labels = torch.tensor(labels)

# Print sentence 0, now as a list of IDs.
print('Original: ', texts[0])
print('Token IDs:', input_ids[0])

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Original:  @AmosFromWV @all_outta_gum @MythSerene @MichelleUgenti As for the ‘20 election, people like you declare that Biden could not have gotten as many votes as he did. Thus fraud occurred. 

Fact: plain and simple: more people HATED Trump than loved him. 

In AZ 10’s of 1000’s of ballots voted straight GOP except for prez. Thus Trump lost.
Token IDs: tensor([  101,  1030, 13744, 19699,  5358,  2860,  2615,  1030,  2035,  1035,
        24955,  1035, 16031,  1030, 17218,  7869,  2638,  1030,  9393, 22890,
        16778,  2004,  2005,  1996,  1520,  2322,  2602,  1010,  2111,  2066,
         2017, 13520,  2008,  7226,  2368,  2071,  2025,  2031,  5407,  2004,
         2116,  4494,  2004,  2002,  2106,  1012,  2947,  9861,  4158,  1012,
         2755,  1024,  5810,  1998,  3722,  1024,  2062,  2111,  6283,  8398,
         2084,  3866,  2032,   102])


## Create train/test/validation splits

Here we split your dataset into 3 parts: a training set, a validation set, and a testing set. Each item in your dataset will be a 3-tuple containing an input_id tensor, an attention_mask tensor, and a label tensor.



In [13]:

total = len(df)

num_train = int(total * .8)
num_val = int(total * .1)
num_test = total - num_train - num_val

# make lists of 3-tuples (already shuffled the dataframe in cell above)

train_set = [(input_ids[i], attention_masks[i], labels[i]) for i in range(num_train)]
val_set = [(input_ids[i], attention_masks[i], labels[i]) for i in range(num_train, num_val+num_train)]
test_set = [(input_ids[i], attention_masks[i], labels[i]) for i in range(num_val + num_train, total)]

train_text = [texts[i] for i in range(num_train)]
val_text = [texts[i] for i in range(num_train, num_val+num_train)]
test_text = [texts[i] for i in range(num_val + num_train, total)]


Here we choose the model we want to finetune from https://huggingface.co/transformers/pretrained_models.html. Because the task requires us to label sentences, we wil be using BertForSequenceClassification below. You may see a warning that states that `some weights of the model checkpoint at [model name] were not used when initializing. . .` This warning is expected and means that you should fine-tune your pre-trained model before using it on your downstream task. See [here](https://github.com/huggingface/transformers/issues/5421#issuecomment-652582854) for more info.

In [14]:
from transformers import BertForSequenceClassification, AdamW, BertConfig

model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased", # Use the 12-layer BERT model, with an uncased vocab.
    num_labels = 3, # The number of output labels.   
    output_attentions = False, # Whether the model returns attentions weights.
    output_hidden_states = False, # Whether the model returns all hidden-states.
)

# Tell pytorch to run this model on the GPU.
model.cuda()


Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, element

# ACTION REQUIRED #

Define your fine-tuning hyperparameters in the cell below (we have randomly picked some values to start with). We want you to experiment with different configurations to find the one that works best (i.e., highest accuracy) on your validation set. Feel free to also change pretrained models to others available in the HuggingFace library (you'll have to modify the cell above to do this). You might find papers on BERT fine-tuning stability (e.g., [Mosbach et al., ICLR 2021](https://openreview.net/pdf?id=nzpLWnVAyah)) to be of interest.

In [51]:
batch_size = 99
optimizer = AdamW(model.parameters(),
                  lr = 5e-5, # args.learning_rate - default is 5e-5
                  eps = 1e-8 # args.adam_epsilon  - default is 1e-8
                )
epochs = 50

# Fine-tune your model
Here we provide code for fine-tuning your model, monitoring the loss, and checking your validation accuracy. Rerun both of the below cells when you change your hyperparameters above.

In [52]:
import numpy as np
# function to get validation accuracy
def get_validation_performance(val_set):
    # Put the model in evaluation mode
    model.eval()

    # Tracking variables 
    total_eval_accuracy = 0
    total_eval_loss = 0

    num_batches = int(len(val_set)/batch_size) + 1

    total_correct = 0

    for i in range(num_batches):

      end_index = min(batch_size * (i+1), len(val_set))

      batch = val_set[i*batch_size:end_index]
      
      if len(batch) == 0: continue

      input_id_tensors = torch.stack([data[0] for data in batch])
      input_mask_tensors = torch.stack([data[1] for data in batch])
      label_tensors = torch.stack([data[2] for data in batch])
      
      # Move tensors to the GPU
      b_input_ids = input_id_tensors.to(device)
      b_input_mask = input_mask_tensors.to(device)
      b_labels = label_tensors.to(device)
        
      # Tell pytorch not to bother with constructing the compute graph during
      # the forward pass, since this is only needed for backprop (training).
      with torch.no_grad():        

        # Forward pass, calculate logit predictions.
        outputs = model(b_input_ids, 
                                token_type_ids=None, 
                                attention_mask=b_input_mask,
                                labels=b_labels)
        loss = outputs.loss
        logits = outputs.logits
            
        # Accumulate the validation loss.
        total_eval_loss += loss.item()
        
        # Move logits and labels to CPU
        logits = logits.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()
        print(label_ids)
        # Calculate the number of correctly labeled examples in batch
        pred_flat = np.argmax(logits, axis=1).flatten()
        labels_flat = label_ids.flatten()
        num_correct = np.sum(pred_flat == labels_flat)
        total_correct += num_correct
        
    # Report the final accuracy for this validation run.
    avg_val_accuracy = total_correct / len(val_set)
    return avg_val_accuracy



In [53]:
import random

# training loop

# For each epoch...
for epoch_i in range(0, epochs):
    # Perform one full pass over the training set.

    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')

    # Reset the total loss for this epoch.
    total_train_loss = 0

    # Put the model into training mode.
    model.train()

    # For each batch of training data...
    num_batches = int(len(train_set)/batch_size) + 1

    for i in range(num_batches):
      end_index = min(batch_size * (i+1), len(train_set))

      batch = train_set[i*batch_size:end_index]

      if len(batch) == 0: continue

      input_id_tensors = torch.stack([data[0] for data in batch])
      input_mask_tensors = torch.stack([data[1] for data in batch])
      label_tensors = torch.stack([data[2] for data in batch])

      # Move tensors to the GPU
      b_input_ids = input_id_tensors.to(device)
      b_input_mask = input_mask_tensors.to(device)
      b_labels = label_tensors.to(device)

      # Clear the previously calculated gradient
      model.zero_grad()        

      # Perform a forward pass (evaluate the model on this training batch).
      outputs = model(b_input_ids, 
                            token_type_ids=None, 
                            attention_mask=b_input_mask, 
                            labels=b_labels)
      loss = outputs.loss
      logits = outputs.logits

      total_train_loss += loss.item()

      # Perform a backward pass to calculate the gradients.
      loss.backward()

      # Update parameters and take a step using the computed gradient.
      optimizer.step()
        
    # ========================================
    #               Validation
    # ========================================
    # After the completion of each training epoch, measure our performance on
    # our validation set. Implement this function in the cell above.
    print(f"Total loss: {total_train_loss}")
    val_acc = get_validation_performance(val_set)
    print(f"Validation accuracy: {val_acc}")
    
print("")
print("Training complete!")



======== Epoch 1 / 50 ========
Training...
Total loss: 9.702323950477876e-06
[1 0 1 1 0 0 0 0 1 1 0]
Validation accuracy: 0.8181818181818182

======== Epoch 2 / 50 ========
Training...
Total loss: 9.271922863263171e-06
[1 0 1 1 0 0 0 0 1 1 0]
Validation accuracy: 0.8181818181818182

======== Epoch 3 / 50 ========
Training...
Total loss: 8.924338544602506e-06
[1 0 1 1 0 0 0 0 1 1 0]
Validation accuracy: 0.8181818181818182

======== Epoch 4 / 50 ========
Training...
Total loss: 8.444995728495996e-06
[1 0 1 1 0 0 0 0 1 1 0]
Validation accuracy: 0.8181818181818182

======== Epoch 5 / 50 ========
Training...
Total loss: 7.728492164460476e-06
[1 0 1 1 0 0 0 0 1 1 0]
Validation accuracy: 0.8181818181818182

======== Epoch 6 / 50 ========
Training...
Total loss: 7.557835033367155e-06
[1 0 1 1 0 0 0 0 1 1 0]
Validation accuracy: 0.8181818181818182

======== Epoch 7 / 50 ========
Training...
Total loss: 6.976852546358714e-06
[1 0 1 1 0 0 0 0 1 1 0]
Validation accuracy: 0.8181818181818182

=====

# Evaluate your model on the test set
After you're satisfied with your hyperparameters (i.e., you're unable to achieve higher validation accuracy by modifying them further), it's time to evaluate your model on the test set! Run the below cell to compute test set accuracy.


In [57]:
get_validation_performance(test_set)

[1 0 1 1 0 0 1 1 1 1 1 0 1]


0.7692307692307693

## Question 2.1 (15 points):
Congratulations! You've now gone through the entire fine-tuning process and created a model for your downstream task. Two more questions left :) First, describe your hyperparameter selection process in words. If you based your process on any research papers or websites, please reference them. Why do you think the hyperparameters you ended up choosing worked better than others? Also, is there a significant discrepancy between your test and validation accuracy? Why do you think this is the case?

### *WRITE YOUR ANSWER HERE*
__We have used adam optimizer, since it worked best compared to other optimizers, increasing the epoch size to 50 increased the test performace to 0.76, also increasing accuracy to 100 decreased test performance.__

## Question 2.2 (25 points):
Finally, perform an *error analysis* on your model. This is good practice for your final project. Write some code in the below code cell to print out the text of up to five test set examples that your model gets **wrong**. If your model gets more than five test examples wrong, randomly choose five of them to analyze. If your model gets fewer than five examples wrong, please design five test examples that fool your model (i.e., *adversarial examples*). Then, in the following text cell, perform a qualitative analysis of these examples. See if you can figure out any reasons for errors that you observe, or if you have any informed guesses (e.g., common linguistic properties of these particular examples). Does this analysis suggest any possible future steps to improve your classifier?
__The classifier couldn't correctly identify Sarcasm, at the same time some tweets had were neutral but were identified as negative__

### *DESCRIBE YOUR QUALITATIVE ANALYSIS OF THE ABOVE EXAMPLES HERE*



---

Finished? Remember to upload the PDF file of this notebook to Gradescope **AND** your dataset files (annotator1.csv, annotator2.csv, annotatorn.csv (where n is the number of members in the group who annotated) and final_data.csv).  When you submit the deliverables, make sure to submit as a group within Gradescope.